### ISSUE TITLE
extention crashes instantly when pressing just "r" in the search bar. 

### ISSUE THREAD

**Issue by backAir** [Attack825/RecentProjectsOpen#3]
The extention crashes instantly every time it's triggered

Here is the requested information from the popup message: 

logs: [2024-12-30.txt](https://github.com/user-attachments/files/18277487/2024-12-30.txt)

exception message:

```
Flow Launcher version: 1.16.1
OS Version: 19045.5247
IntPtr Length: 8
x64: True

Python Path: C:\Users\tonyl\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 12/30/2024 21:08:53
Exception:
RecentProjectsOpen Exception: 
Websites: https://github.com/Attack825/RecentProjectsOpen
Author: Attack825
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\tonyl\AppData\Roaming\FlowLauncher\Plugins\RecentProjectsOpen-1.0.0\main.py", line 12, in <module>
    from plugin.main import RecentProjectsOpen  # noqa: E402
  File "C:\Users\tonyl\AppData\Roaming\FlowLauncher\Plugins\RecentProjectsOpen-1.0.0\plugin\main.py", line 6, in <module>
    from click import UsageError
ModuleNotFoundError: No module named 'click'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\tonyl\AppData\Roaming\FlowLauncher\Plugins\RecentProjectsOpen-1.0.0\main.py", line 12, in <module>
    from plugin.main import RecentProjectsOpen  # noqa: E402
  File "C:\Users\tonyl\AppData\Roaming\FlowLauncher\Plugins\RecentProjectsOpen-1.0.0\plugin\main.py", line 6, in <module>
    from click import UsageError
ModuleNotFoundError: No module named 'click'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 297
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 297
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 313
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Attack825** [comment]
Thank you for bringing this issue.The `RecentProjectsOpen` plugin is failing because it requires the 'click' module, which is not currently installed in the Python environment.

By updating the `requirements.txt` file within the project, I have ensured that all necessary dependencies, including the 'click' module, are properly installed and available for the plugin to function correctly.

If you have any further questions or need additional assistance, please don't hesitate to reach out.
